### ISSUE TITLE
Admin "view on site" always points at live site

### ISSUE THREAD

**Issue by cpolcyn** [SalesforceFoundation/mrbelvedereci#56]
When running locally "view on site" from admin pages should go to localhost:8000 instead of the live site.

**Comment by cdcarter** [comment]
Turns out, this is config! Update the "Site" in Django admin to whatever your localhost is:

<img width="585" alt="screen shot 2017-08-18 at 9 53 04 am" src="https://user-images.githubusercontent.com/164/29468927-0d7332e4-83fb-11e7-875a-0171f9472f56.png">

**Comment by cdcarter** [comment]
didn't mean to close, not sure if this is sufficient @cpolcyn

**Comment by cpolcyn** [comment]
Yep all good. thanks!

**Comment by cpolcyn** [comment]
Okay I spoke prematurely… Still not working for me. In my local db I already had 2 sites:
![screen shot 2017-08-18 at 10 03 44 am](https://user-images.githubusercontent.com/11445853/29469331-93d31402-83fc-11e7-996b-5f2ebd9ede7c.png)

When I hover over a "view on site" button it shows a localhost link but ultimately it still ends up at the live site.

**Comment by cdcarter** [comment]
I renamed my "mrbelvedereci.herokuapp.com" domain to "localhost:8000" and only have the one entry.

**Comment by cpolcyn** [comment]
Have you verified the "view on site" button works for you locally?

**Comment by cdcarter** [comment]
![djangoadmin](https://user-images.githubusercontent.com/164/29471158-cd372ab0-8403-11e7-94b6-103f314d3192.gif)

yes, with the single site entry.

**Comment by cpolcyn** [comment]
Thanks for confirming. I messed up my local db by just outright deleting the mrbelvedereci entry but I was using sqlite and want to transition to postgres anyway, so this just means I will do that sooner :)
